/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rivermonitoringservice;

import rivermonitoringservice.mqtt.MqttManager;
import rivermonitoringservice.serial.SerialCommunicator;
import rivermonitoringservice.webServer.RiverMonitoringDashboardApplication;

public class RiverMonitoringService {
    private static final RiverMonitoringDashboardApplication dashboard = new RiverMonitoringDashboardApplication();
    private static final MqttManager mqttServer = new MqttManager();
    private static final SerialCommunicator serialCommunicator = new SerialCommunicator();

    public String getGreeting() {
        return "Hello World!2";
    }

    public static void main(String[] args) {
        setup(args);
        System.out.println(new RiverMonitoringService().getGreeting());
        
    }

    // TODO: serial communication
    public static void updateChannelController() {}

    public static void updateDashboard(final double waterLevel, final int valveOpeningPercentage, final String currentState) {
        // TODO: consider avoiding casting to int by allowing the dashboard to work with double data types
        RiverMonitoringService.dashboard.setWaterLevel((int) waterLevel);
        RiverMonitoringService.dashboard.setOpeningGatePercentage(valveOpeningPercentage);
        RiverMonitoringService.dashboard.setStatus(currentState);
    }

    private static void setup(String[] args) {
        RiverMonitoringService.dashboard.startWebServer(args);
        RiverMonitoringService.mqttServer.startMqttServer();
        serialCommunicator.start();
    }
}
